# Generated by Django 5.0.2 on 2024-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('accountno', models.IntegerField(primary_key=True, serialize=False)),
                ('cardholdername', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('depositedammount', models.IntegerField()),
                ('accountopendate', models.DateField()),
            ],
        ),
    ]
